In [53]:
import numpy as np
import math

In [183]:
def fill_matrix(matrix):
    rows, cols = matrix.shape
    print(f"Enter values for a {rows}x{cols} matrix:")
    
    for i in range(rows):
        for j in range(cols):
            if i == j and cols != 1:
                continue
            if j > i:
                matrix[i, j] = float(input(f"Enter value for element at position ({i+1}, {j+1}): "))
                matrix[j, i] = 1 / matrix[i, j]
                
            if cols == 1:
                matrix[i, j] = float(input(f"Enter value for element at position ({i+1}, {j+1}): "))
                
    
    return np.array(matrix)

In [176]:
number_of_criteria = 3

comparison_matrix = np.ones((number_of_criteria, number_of_criteria))
comparison_matrix = fill_matrix(comparison_matrix)
comparison_matrix

Enter values for a 3x3 matrix:


array([[1.        , 0.5       , 3.        ],
       [2.        , 1.        , 4.        ],
       [0.33333333, 0.25      , 1.        ]])

In [177]:
epsilon = math.pi* 10 **(-5)
epsilon

3.1415926535897935e-05

In [145]:
def find_eigenvector(epsilon, A):
    n, c = A.shape
    x0 = np.ones((n, 1))
    y = x0

    lambda_score = np.dot(y.T, x0)
    lambda_score[0][0]
    l2_norm = math.inf

    if c == 1:
        norm = np.linalg.norm(A)
        return (A / norm), _
       
    while (l2_norm >= epsilon):
        x = (1/np.linalg.norm(y, 2))*y
        y = np.matmul(A, x)
        lambda_score = np.dot(y.T, x)
        diff_vector = y - lambda_score[0][0]*x
        l2_norm = np.linalg.norm(diff_vector, 2)
    
    return x, lambda_score
    

In [178]:
criteria_eigenvector, lambda_max = find_eigenvector(epsilon, comparison_matrix)
print(criteria_eigenvector)

print(f"Most preffered criteria: {np.argmax(criteria_eigenvector) + 1}")


[[0.488058  ]
 [0.85271238]
 [0.18622833]]
Most preffered criteria: 2


In [179]:
RI = [0, 0, 0.58, 0.9, 1.12, 1.24, 1.32, 1.41, 1.45, 1.49]
CI = (lambda_max - number_of_criteria) / (number_of_criteria - 1)
CR = CI / RI[number_of_criteria - 1]

print(f"CR: {CR[0]}")
if CR < 0.1:
    print(f"Data is Saaty consistent")
else:
    print(f"Data is not Saaty consistent")

CR: [0.01577306]
Data is Saaty consistent


In [184]:
number_of_alternatives = 4
alt_matrices = []
for i in range(number_of_criteria):
    flag = input("Do you want a column matrix? (Answer: yes or no)")
    if flag == "yes":
        alternative_matrix = np.ones((number_of_alternatives, 1))
    else:
        alternative_matrix = np.ones((number_of_alternatives, number_of_alternatives))

    alternative_matrix = fill_matrix(alternative_matrix)
    alt_matrices.append(alternative_matrix)

Enter values for a 4x4 matrix:
Enter values for a 4x4 matrix:
Enter values for a 4x1 matrix:


In [185]:
alt_matrices

[array([[1.        , 0.25      , 4.        , 0.16666667],
        [4.        , 1.        , 4.        , 0.25      ],
        [0.25      , 0.25      , 1.        , 0.2       ],
        [5.99999999, 4.        , 5.        , 1.        ]]),
 array([[1.        , 2.        , 5.        , 1.        ],
        [0.5       , 1.        , 3.        , 2.        ],
        [0.2       , 0.33333333, 1.        , 0.25      ],
        [1.        , 0.5       , 4.        , 1.        ]]),
 array([[150.],
        [170.],
        [162.],
        [185.]])]

In [186]:
eigenvectors = []

for i in range(len(alt_matrices)):
    alt_eigenvector = find_eigenvector(epsilon, alt_matrices[i])[0]
    
    best_choice_for_alt = np.argmax(alt_eigenvector) + 1
    print(f"Best choice for alternative {i + 1} is {best_choice_for_alt}")
    eigenvectors.append(alt_eigenvector)

Best choice for alternative 1 is 4
Best choice for alternative 2 is 1
Best choice for alternative 3 is 4


In [187]:
eigenvectors

[array([[0.18069624],
        [0.38495897],
        [0.09359041],
        [0.90022014]]),
 array([[0.69225925],
        [0.53052591],
        [0.13562027],
        [0.47002823]]),
 array([[0.44847308],
        [0.50826949],
        [0.48435093],
        [0.5531168 ]])]

In [188]:
stacked_matrix = np.hstack(eigenvectors)
stacked_matrix

array([[0.18069624, 0.69225925, 0.44847308],
       [0.38495897, 0.53052591, 0.50826949],
       [0.09359041, 0.13562027, 0.48435093],
       [0.90022014, 0.47002823, 0.5531168 ]])

In [189]:
result_matrix = np.matmul(stacked_matrix, criteria_eigenvector)
print(result_matrix)
print(f"We should choose alternative {np.argmax(result_matrix) + 1}")

[[0.76200666]
 [0.73492249]
 [0.2515225 ]
 [0.94316455]]
We should choose alternative 4
